spring:
  config:
    activate:
      on-profile: aws-dev

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:default-bucket}
    presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:180} # in seconds
    region: ${AWS_S3_REGION:ap-northeast-2}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
