spring:
  config:
    activate:
      on-profile: db-dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: ${DB_URL:jdbc:mysql://localhost:3306/climbx?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USER:dev_user}
    password: ${DB_PASSWORD:dev_password}
    
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      auto-commit: false
      connection-timeout: 20000
      validation-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

  sql:
    init:
        mode: always
        platform: mysql
        encoding: UTF-8
        schema-locations: []
        data-locations:
            - classpath:db/init/*.sql