# OAuth2 설정
spring:
  security:
    oauth2:
      kakao:
        client:
          client-id: ${KAKAO_REST_API_KEY}
          client-secret: ${KAKAO_CLIENT_SECRET}
          # 개발 테스트용 redirect-uri
          redirect-uri: "http://localhost:8080/test-callback.html"
          # 실제 적용될 형태
          # redirect-uri: "myapp://callback"
        provider:
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me

# JWT 설정
auth:
  jwt:
    secret: ${JWT_SECRET:default-secret-key-for-development-only-change-in-production}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600} # 1시간 (초 단위)
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1209600} # 2주 (초 단위)
    issuer: ${JWT_ISSUER:climbx-api-dev}

# 로깅 설정
logging:
  level:
    org.springframework.security.oauth2: DEBUG
    com.climbx.climbx.auth: DEBUG