spring:
  profiles:
    active: dev
    group:
      dev:
        - db-dev

  jpa:
    open-in-view: false
    properties:
      javax.persistence.validation.mode: CALLBACK
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

server:
  port: 8080

auth:
  fixed-jwt: ${FIXED_JWT:default-jwt-token}

logging:
  level:
    root: INFO
    com.climbx: INFO