# OAuth2 설정
spring:
  security:
    oauth2:
      # Kakao OAuth2 설정

      kakao:
        jwks-uri: https://kauth.kakao.com/.well-known/jwks.json
        issuer: https://kauth.kakao.com
        audience: ${KAKAO_NATIVE_APP_KEY}

      # Google OAuth2 설정 예시 (주석 해제 후 사용)
      # google:
      #   client:
      #     client-id: ${GOOGLE_CLIENT_ID}
      #     client-secret: ${GOOGLE_CLIENT_SECRET}
      #     jwks-uri: https://www.googleapis.com/oauth2/v3/certs
      #     issuer: https://accounts.google.com
      
      # Naver OAuth2 설정 예시 (주석 해제 후 사용)
      # naver:
      #   client:
      #     client-id: ${NAVER_CLIENT_ID}
      #     client-secret: ${NAVER_CLIENT_SECRET}
      #     jwks-uri: https://nid.naver.com/.well-known/jwks.json
      #     issuer: https://nid.naver.com 

# JWT 설정
auth:
  jwt:
    secret: ${JWT_SECRET:default-secret-key-for-development-only-change-in-production}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600} # 1시간 (초 단위)
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1209600} # 2주 (초 단위)
    issuer: ${JWT_ISSUER:https://climbx-api-dev/}
    audience: ${JWT_AUDIENCE:climbx-client}
    jws-algorithm: ${JWT_JWS_ALGORITHM:HS256}

# 로깅 설정
logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.climbx.climbx.auth: DEBUG